apiVersion: v1
kind: Secret
metadata:
  name: azdo-pat
  namespace: apps-public           # ← same ns as your pods
type: Opaque
stringData:
  GIT_USERNAME: "pat"              # or your DevOps username
  GIT_PASSWORD: <YOUR_PERSONAL_ACCESS_TOKEN>  # 40-character Personal Access Token
