###############################################################################
# secretproviderclass.yaml  (aka “service-provider-class”)
###############################################################################
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: navav2-kv
  namespace: apps-public                # match your SA / pods
spec:
  provider: azure
  parameters:
    # ─── Where the secrets live ────────────────────────────────────────────
    keyvaultName: navav2-kv             # Azure Key Vault name
    tenantId: <aad-tenant-guid>
    # Workload Identity: the CSI driver uses the client-id annotated on the
    # ServiceAccount (navav2-sa) so no clientId field is required.
    useWorkloadIdentity: "true"
    # ─── What to pull ──────────────────────────────────────────────────────
    objects: |
      array:
        - |
          objectName: sql-server
          objectType: secret
        - |
          objectName: tenant-id
          objectType: secret
        - |
          objectName: auth0-domain
          objectType: secret
        - |
          objectName: workload-id-client-id
          objectType: secret
  # ─── Mirror into a K8s Secret for env-var consumption ────────────────────
  secretObjects:
    - secretName: navav2-secrets         # <- your deployments already use this
      type: Opaque
      data:
        - objectName: sql-server
          key: sql-server
        - objectName: tenant-id
          key: tenant-id
        - objectName: auth0-domain
          key: auth0-domain
        - objectName: workload-id-client-id
          key: workload-id-client-id
