###############################################################################
# service-account.yaml – binds the pod to the Azure-AD app registration
###############################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: navav2-sa                          # ← must match spec.template.spec.serviceAccountName
  namespace: apps-public                   # keep consistent with your other YAMLs
  annotations:
    # Client-ID (GUID) of the Azure AD application that has the federated-
    # identity credential pointing at this SA / namespace / cluster OIDC issuer
    azure.workload.identity/client-id: "<AAD-app-client-id>"
    # If your AKS cluster is linked to a *different* tenant than the AAD app,
    # uncomment the next line:
    # azure.workload.identity/tenant-id: "<tenant-guid>"
  labels:
    azure.workload.identity/use: "true"
